### ISSUE TITLE
Module parse error

### ISSUE THREAD

**Issue by BYulia** [bitcoinjs/ecpair#10]
I have trouble with parse ecpair module. 
I can temporarily solve it by removing the property class description lines.
I use ecpair with Nuxt.js
![Monosnap 2022-08-12 16-48-12](https://user-images.githubusercontent.com/9570494/184381220-0f7fb15e-f11f-41cc-86f1-0ce542108474.png)

**Comment by junderw** [comment]
your webpack settings are incorrect.

Please ask in a webpack forum.
