### ISSUE TITLE
New testEcc tests in 2.1.0 break @noble/secp256k1

### ISSUE THREAD

**Issue by landabaso** [bitcoinjs/ecpair#13]
[Ecpair 2.1.0 `testEcc`](https://github.com/bitcoinjs/ecpair/blob/master/src/testecc.js#L46) has additional new tests with code like this:

```javascript
ecc.privateAdd(
        h('0000000000000000000000000000000000000000000000000000000000000001'),
        h('0000000000000000000000000000000000000000000000000000000000000000'),
      )
```

which breaks noble-secp256k1, because noble expects the private key > 0.

See:
https://github.com/paulmillr/noble-secp256k1/blob/1.7.0/index.ts#L1024

I understand this is not strictly a bug. Or is it?
Anyway, I thought about sharing this with you in case you agree on tweaking the tests to avoid 0 priv keys.

**Comment by junderw** [comment]
I don't see any code for privateAdd, so I assume this is a bug in the wrapper code you created/use.

privateAdd args are (privkey, scalar) so the second arg can be from 0 to 2^256-1 (in hex, all 0s up to all fs).

Please file a bug report with whoever maintains the wrapper.

**Comment by landabaso** [comment]
You're right. I just did. Thanks!

**Comment by landabaso** [comment]
I don't want to open another issue because I somehow feel this is something related.

I'm still working to make noble & ecpair work together after new versions of both libraries.

There's [this other test](https://github.com/bitcoinjs/ecpair/blob/master/src/testecc.js#L56) in ecpair:

```javascript
  // -3 + 3 == 0
  assert(
    ecc.privateAdd(
      h('fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413e'),
      h('0000000000000000000000000000000000000000000000000000000000000003'),
    ) === null,
  );
```

I end up having a point that is zero but not a `null`. 
Does it need to return `null` because this operation is invalid (& noble should throw)?
I'm struggling with this one because noble detects the point to be valid and I get a zero. cc/ @paulmillr @junderw .

**Comment by junderw** [comment]
Yes. The output of privateAdd is a privateKey. And 0 is an invalid privateKey which should return null.
