### ISSUE TITLE
Bug when using browserify

### ISSUE THREAD

**Issue by Anderson-Juhasc** [bitcoinjs/ecpair#15]
I just imported the lib and compile with browserify, but:

![Screenshot from 2022-12-08 10-42-04](https://user-images.githubusercontent.com/423705/206461460-a995bc73-1457-408f-93bd-8685abfac1f8.png)

Any idea?

**Comment by junderw** [comment]
Need steps to reproduce.

Versions of things (like browserify), commands, etc etc.

Whatever you did, the bundler did not recognize the browser files and tried to bundle the NodeJS files instead.

**Comment by junderw** [comment]
node version, npm version, browserify version, what commands / configs did you use for the bundling.

etc etc etc

**Comment by junderw** [comment]
Also, this issue is with tiny-secp256k1, not ecpair. So I'm closing it here.

Please open an issue in the appropriate repo with more info. Thanks.

Also search for existing issues (this sounds familiar)

**Comment by Anderson-Juhasc** [comment]
node: v16.18.1
npm: 7.12.0
browserify: v17.0.0

I just run `browserify file.js -o bundle.js` with it:

`const ecc = require('tiny-secp256k1')`

**Comment by Anderson-Juhasc** [comment]
@junderw sorry, you right!
