### ISSUE TITLE
keyPair.chainCode does not exists

### ISSUE THREAD

**Issue by 0xcielo** [bitcoinjs/ecpair#18]
const keyPair = ECPair.fromWIF(privateKey, network);
bip32.fromPrivateKey(keyPair.privateKey, keyPair.chainCode, network);

I need keyPair.chainCode, and does not exists, how to retrieve?

**Comment by junderw** [comment]
Chain code is a concept that solely exists in BIP32.

ECPairs are just simple ECDSA key pairs.

There is no way to get a chain code from an ECPair.

Please read BIP32 for further information on what the chain code is and how it is generated.

[The text of BIP32 is here.](https://github.com/bitcoin/bips/blob/e918b50731397872ad2922a1b08a5a4cd1d6d546/bip-0002.mediawiki)
