### ISSUE TITLE
Undefined fromWIF

### ISSUE THREAD

**Issue by OxMarco** [bitcoinjs/ecpair#19]
I am testing the wallet derivation from a WIF string.
```typescript
import * as ecc from '@bitcoin-js/tiny-secp256k1-asmjs';
const network = bitcoin.networks.bitcoin;

const wif: string = "WIF";
const ECPair: ECPairAPI = ECPairFactory(ecc);
const keyPair: ECPairInterface = ECPair.fromWIF(wif, network);
```
However, the example code returns an error: *Cannot read properties of undefined (reading 'call')*

**Comment by junderw** [comment]
I tried your code and it works.

Can you please post your version info. node, npm, bitcoinjs-lib, ecpair, etc.

```ts
import * as ecc from '@bitcoin-js/tiny-secp256k1-asmjs';
import * as bitcoin from 'bitcoinjs-lib';
import { ECPairAPI, ECPairFactory, ECPairInterface } from 'ecpair';

const network = bitcoin.networks.bitcoin;
const ECPair: ECPairAPI = ECPairFactory(ecc);

const wif: string = "L4rK1yDtCWekvXuE6oXD9jCYfFNV2cWRpVuPLBcCU2z8TrisoyY1";
const keyPair: ECPairInterface = ECPair.fromWIF(wif, network);
```

**Comment by OxMarco** [comment]
### dependencies and system info:
- `macOS 13.4`
- `node v20.5.1`
- `npm v9.8.0`
- `"@bitcoin-js/tiny-secp256k1-asmjs": "^2.2.3"`
- `"bitcoinjs-lib": "^6.1.5"`
- `"ecpair": "^2.1.0"`

### test code:
```typescript
import * as ecc from '@bitcoin-js/tiny-secp256k1-asmjs';
import * as bitcoin from 'bitcoinjs-lib';
import { ECPairFactory, ECPairAPI, ECPairInterface } from 'ecpair';

function test() {
// bitcoin.initEccLib(ecc) <= tried adding this line too, still got the same error
  const network = bitcoin.networks.bitcoin;
  const ECPair: ECPairAPI = ECPairFactory(ecc);
  const wif: string = "L4rK1yDtCWekvXuE6oXD9jCYfFNV2cWRpVuPLBcCU2z8TrisoyY1";
  const rootKey: ECPairInterface = ECPair.fromWIF(wif, network);
  console.log("keypair", rootKey)
}
```

**Comment by OxMarco** [comment]
Any idea how we can get the WIF import to work? Thanks 🙏

**Comment by junderw** [comment]
It still works for me...

I used the same version for everything except macos (I use Linux)

A majority of users of this library are probably on MacOS, so I doubt it has to do with the OS.

Is this *all* of the code?

**Comment by OxMarco** [comment]
Solved, it was a problem with vite polyfill. Thanks!

**Comment by smoreweb** [comment]
I have the same problem, how did you solve it?
