### ISSUE TITLE
Module parse failed: Unexpected token (80:7)

### ISSUE THREAD

**Issue by yerramreddyuday** [bitcoinjs/ecpair#9]
> Failed to compile.

> ./node_modules/ecpair/src/ecpair.js 80:7
> Module parse failed: Unexpected token (80:7)
> File was processed with these loaders:
> * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
> | 
> |   class ECPair {
>     __D;
> |     __Q;
> |     compressed;

Can anyone help me with this issue? I don't see any issue in general ts repository but generating the above issue in react application.

Node version used : v16.10.0

Could you please share your thoughts and let me know what exactly need to be done to get rid of the issue. ( Also add what need to added as dependencies in package.json and data in tsconfig.json )

**Comment by junderw** [comment]
duplicate #2
